const STORAGE_KEY='chengc_posts';let currentFilter='all',searchQuery='',posts=[];
function loadPosts(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');posts=Array.isArray(p)?p.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.content==='string'&&typeof x.date==='string'&&['study','life'].includes(x.category)):[]}catch(e){console.warn('记录数据无法读取。',e);posts=[]}}
function savePosts(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(posts));return true}catch(e){console.error('记录保存失败。',e);alert('保存失败：浏览器存储空间可能已满。');return false}}
function escapeHtml(text){const div=document.createElement('div');div.textContent=String(text);return div.innerHTML}
function visiblePosts(){return posts.filter(p=>(currentFilter==='all'||p.category===currentFilter)&&(!searchQuery||`${p.title} ${p.content}`.toLowerCase().includes(searchQuery)))}
function renderPosts(){const box=document.getElementById('postsContainer'),shown=visiblePosts();document.getElementById('postCount').textContent=`共 ${shown.length} 条`;if(!shown.length){const title=searchQuery?'没有找到匹配记录':currentFilter==='all'?'还没有任何记录':'这个分类暂无记录';box.innerHTML=`<div class="empty-state"><strong>${title}</strong><p>${searchQuery?'换个关键词试试。':'点击导航中的“写记录”，留下此刻的想法。'}</p></div>`;return}box.innerHTML=shown.map(p=>`<article class="post-card"><div class="post-tags"><span class="post-tag tag-${p.category}">${p.category==='study'?'学习':'生活'}</span></div><time class="post-date">${escapeHtml(p.date)}</time><h3 class="post-title">${escapeHtml(p.title)}</h3><p class="post-content">${escapeHtml(p.content)}</p><div class="post-actions"><button class="delete-btn" type="button" data-delete-id="${escapeHtml(p.id)}" aria-label="删除《${escapeHtml(p.title)}》">删除</button></div></article>`).join('')}
function setFilter(filter){currentFilter=filter;document.querySelectorAll('.filter-btn').forEach(b=>{const active=b.dataset.filter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});renderPosts()}
function addPost(title,category,content){posts.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),title:title.trim(),category,content:content.trim(),date:new Date().toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})});if(savePosts())renderPosts()}
function deletePost(id){if(!confirm('确定要删除这条记录吗？'))return;posts=posts.filter(p=>p.id!==id);if(savePosts())renderPosts()}
function applyTheme(theme){document.documentElement.classList.toggle('light',theme==='light');document.documentElement.classList.toggle('dark',theme!=='light');document.querySelector('meta[name="theme-color"]').content=theme==='light'?'#f7f5fb':'#090910'}
const savedTheme=localStorage.getItem('theme');applyTheme(savedTheme||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));document.getElementById('themeToggle').addEventListener('click',()=>{const next=document.documentElement.classList.contains('dark')?'light':'dark';applyTheme(next);localStorage.setItem('theme',next)});
const menuToggle=document.getElementById('menuToggle'),navLinks=document.getElementById('navLinks');menuToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'关闭导航菜单':'打开导航菜单')});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));
const modal=document.getElementById('modalOverlay'),titleInput=document.getElementById('title');let lastFocusedElement=null;function openModal(){lastFocusedElement=document.activeElement;modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');requestAnimationFrame(()=>titleInput.focus())}function closeModal(){modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(lastFocusedElement)lastFocusedElement.focus()}
document.getElementById('writeBtn').addEventListener('click',openModal);document.getElementById('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.classList.contains('hidden'))closeModal()});
document.getElementById('postForm').addEventListener('submit',function(e){e.preventDefault();const title=titleInput.value,category=document.getElementById('category').value,content=document.getElementById('content').value;if(!title.trim()||!content.trim())return;addPost(title,category,content);this.reset();closeModal()});
document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));document.getElementById('searchInput').addEventListener('input',e=>{searchQuery=e.target.value.trim().toLowerCase();renderPosts()});document.getElementById('postsContainer').addEventListener('click',e=>{const b=e.target.closest('[data-delete-id]');if(b)deletePost(b.dataset.deleteId)});loadPosts();renderPosts();
