"""Refresh the static full-text index after editing or adding a posts/*.html page."""
from html.parser import HTMLParser
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]


class ArticleText(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.depth = 0
        self.body_depth = None
        self.parts = []

    def handle_starttag(self, tag, attrs):
        if tag in {"br", "hr", "img", "input", "meta", "link", "source", "wbr"}:
            self.parts.append(" ") if self.body_depth is not None else None
            return
        self.depth += 1
        if "article-body" in dict(attrs).get("class", "").split():
            self.body_depth = self.depth
        if self.body_depth is not None:
            self.parts.append(" ")

    def handle_endtag(self, tag):
        if tag in {"br", "hr", "img", "input", "meta", "link", "source", "wbr"}:
            return
        if self.depth == self.body_depth:
            self.body_depth = None
        self.depth -= 1
        self.parts.append(" ")

    def handle_data(self, data):
        if self.body_depth is not None:
            self.parts.append(data)


def build():
    entries = []
    for page in sorted((ROOT / "posts").glob("*.html")):
        parser = ArticleText()
        parser.feed(page.read_text(encoding="utf-8"))
        text = re.sub(r"\s+", " ", "".join(parser.parts)).strip()
        if not text:
            raise ValueError(f"Missing article-body in {page.name}")
        entries.append({"id": page.stem, "text": text})
    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    target = ROOT / "js" / "blog-search-index.js"
    target.write_text("/* Generated by preview/build-blog-search-index.py. */\n"
                      + "globalThis.ChenCBlogIndex=" + payload + ";\n", encoding="utf-8")
    print(f"Indexed {len(entries)} articles; {target.stat().st_size:,} bytes.")


if __name__ == "__main__":
    build()
