/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteToSitePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultCategory: "\u5B66\u4E60",
  leadMaxChars: 120,
  includeOutline: true,
  includeMindMap: true,
  outputFolder: "\u7F51\u7AD9\u8F93\u51FA",
  siteName: "ChengC",
  homeHref: "../index.html",
  cssPath: "../css/style.css",
  titleSuffix: " \xB7 ChengC",
  aiEnabled: false,
  aiBaseUrl: "https://api.openai.com/v1",
  aiApiKey: "",
  aiModel: "gpt-4o-mini",
  aiPrompt: [
    "\u4F60\u662F\u4E00\u4F4D\u4E2A\u4EBA\u7F51\u7AD9\u7F16\u8F91\u3002\u8BF7\u4E3A\u4E0B\u9762\u7684\u7B14\u8BB0\u5199 1~3 \u53E5\u5BFC\u8BED\uFF08\u6587\u7AE0\u6458\u8981\uFF09\uFF0C\u5B83\u4F1A\u76F4\u63A5\u653E\u5728\u6587\u7AE0\u5F00\u5934\u3002",
    "\u8981\u6C42\uFF1A",
    "1. \u7528\u81EA\u7136\u3001\u53E3\u8BED\u5316\u7684\u4E2D\u6587\u76F4\u63A5\u603B\u7ED3\u5185\u5BB9\uFF0C\u4E0D\u8981\u51FA\u73B0\u201C\u672C\u6587\u201D\u201C\u8FD9\u7BC7\u6587\u7AE0\u201D\u201C\u4EE5\u4E0B\u201D\u201C\u9996\u5148\u201D\u7B49\u5957\u8BDD\uFF1B",
    "2. \u957F\u5EA6\u63A7\u5236\u5728 80~120 \u5B57\uFF1B",
    "3. \u53EA\u8F93\u51FA\u5BFC\u8BED\u672C\u8EAB\uFF0C\u4E0D\u8981\u4EFB\u4F55\u524D\u7F00\u3001\u6807\u9898\u6216\u89E3\u91CA\u3002",
    "",
    "\u7B14\u8BB0\u6807\u9898\uFF1A{{title}}",
    "",
    "\u7B14\u8BB0\u5185\u5BB9\uFF1A",
    "{{content}}"
  ].join("\n")
};
var MINDMAP_COLORS = [
  "#3b82f6",
  // 蓝
  "#ef4444",
  // 红
  "#22c55e",
  // 绿
  "#f59e0b",
  // 琥珀
  "#8b5cf6",
  // 紫
  "#ec4899",
  // 粉
  "#06b6d4",
  // 青
  "#f97316"
  // 橙
];
var MINDMAP_CSS = `
.mm-wrap{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:20px 12px;overflow-x:auto;margin:16px 0}
.mm-tree,.mm-tree ul,.mm-tree li{margin:0;padding:0;list-style:none}
.mm-tree ul{padding-top:16px;position:relative;display:flex;justify-content:flex-start;align-items:flex-start;min-width:max-content}
.mm-tree li{position:relative;padding:16px 8px 0;text-align:center;min-width:0}
.mm-tree li::before,.mm-tree li::after{content:"";position:absolute;top:0;height:16px;width:50%;border-top:2px solid #cbd5e1}
.mm-tree li::before{right:50%}
.mm-tree li::after{left:50%;border-left:2px solid #cbd5e1}
.mm-tree li:only-child::before,.mm-tree li:only-child::after{display:none}
.mm-tree li:only-child{padding-top:0}
.mm-tree li:first-child::before,.mm-tree li:last-child::after{border:0 none}
.mm-tree li:last-child::before{border-right:2px solid #cbd5e1;border-radius:0 6px 0 0}
.mm-tree li:first-child::after{border-radius:6px 0 0 0}
.mm-tree ul ul::before{content:"";position:absolute;top:0;left:50%;width:0;height:16px;border-left:2px solid #cbd5e1}
.mm-tree .mm-node{display:inline-block;border:2px solid var(--mmc,#3b82f6);border-radius:8px;padding:5px 12px;font-size:13px;line-height:1.45;background:#fff;color:var(--mmc,#3b82f6);font-weight:600;max-width:230px;word-break:break-word;vertical-align:top}
.mm-tree .mm-root{background:var(--mmc,#111827);border-color:var(--mmc,#111827);color:#fff;font-size:15px;font-weight:700}
.mm-tree .mm-l2{border-width:1.5px;font-weight:500;opacity:.92;font-size:12.5px}
`;
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function stripMarkdown(s) {
  return s.replace(/```[\s\S]*?```/g, " ").replace(/`([^`]*)`/g, "$1").replace(/!\[[^\]]*\]\([^)]*\)/g, " ").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1").replace(/^#{1,6}\s*/gm, "").replace(/[*_~>#|]/g, "").replace(/[\r\n]+/g, " ").replace(/\s+/g, " ").trim();
}
function estimateReadingTime(text) {
  const cjk = (text.match(/[\u4e00-\u9fff\u3400-\u4dbf]/g) || []).length;
  const words = (text.replace(/[\u4e00-\u9fff\u3400-\u4dbf]/g, " ").match(/[A-Za-z0-9]+/g) || []).length;
  return Math.max(1, Math.round((cjk + words) / 400));
}
function extractLead(content, maxChars) {
  const lines = content.split(/\r?\n/);
  const paragraphs = [];
  let buffer = [];
  let inCode = false;
  for (const line of lines) {
    const t = line.trim();
    if (/^```/.test(t)) {
      inCode = !inCode;
      continue;
    }
    if (inCode) continue;
    if (!t) {
      if (buffer.length) {
        paragraphs.push(buffer.join(" "));
        buffer = [];
      }
      continue;
    }
    if (/^#{1,6}\s/.test(t)) continue;
    if (/^[-*+]\s/.test(t)) continue;
    if (/^\d+[.、)]\s/.test(t)) continue;
    if (/^>\s?/.test(t)) continue;
    if (/^---$/.test(t)) continue;
    buffer.push(t);
  }
  if (buffer.length) paragraphs.push(buffer.join(" "));
  let lead = "";
  for (const p of paragraphs) {
    const clean = stripMarkdown(p);
    if (!clean) continue;
    if (!lead) {
      lead = clean;
      continue;
    }
    if (lead.length >= 30 || lead.length + clean.length > maxChars) break;
    lead = `${lead} ${clean}`;
  }
  if (lead.length > maxChars) {
    const cut = lead.slice(0, maxChars);
    const lastPunct = Math.max(
      cut.lastIndexOf("\u3002"),
      cut.lastIndexOf("\uFF01"),
      cut.lastIndexOf("\uFF1F"),
      cut.lastIndexOf("."),
      cut.lastIndexOf("!")
    );
    lead = lastPunct > maxChars * 0.4 ? cut.slice(0, lastPunct + 1) : cut.replace(/[，、,;；\s]+$/, "") + "\u2026\u2026";
  }
  return lead || "\uFF08\u6682\u65E0\u6458\u8981\uFF1A\u7B14\u8BB0\u6B63\u6587\u4F3C\u4E4E\u4E3A\u7A7A\uFF09";
}
function slugify(title) {
  return title.trim().replace(/[\\/:*?"<>|#^[\]{}]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-");
}
function collectHeadingsWithLevel(text) {
  const out = [];
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^(#{2,3})\s+(.*)$/);
    if (m && m[2].trim()) {
      const clean = stripMarkdown(m[2].trim());
      if (clean) out.push({ level: m[1].length === 2 ? 2 : 3, text: clean });
    }
  }
  return out;
}
function buildMindTree(title, headings) {
  const root = { label: title, children: [] };
  let current = null;
  for (const h of headings) {
    if (h.level === 2) {
      current = { label: h.text, children: [] };
      root.children.push(current);
    } else if (h.level === 3) {
      (current != null ? current : root).children.push({ label: h.text, children: [] });
    }
  }
  return root;
}
function renderMindTree(tree, depth = 0, colorIndex = 0) {
  const isRoot = depth === 0;
  const cls = isRoot ? "mm-root" : depth === 1 ? "mm-l1" : "mm-l2";
  const color = isRoot ? "#111827" : MINDMAP_COLORS[colorIndex % MINDMAP_COLORS.length];
  const liStyle = depth <= 1 ? ` style="--mmc:${color}"` : "";
  const children = tree.children.length ? "\n        <ul>" + tree.children.map((c, i) => renderMindTree(c, depth + 1, depth === 0 ? i : 0)).join("") + "\n        </ul>" : "";
  return `
          <li${liStyle}><div class="mm-node ${cls}">${escapeHtml(tree.label)}</div>${children}</li>`;
}
function parseFrontmatter(content) {
  const m = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return null;
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([^:#\s][^:]*):\s*(.*)$/);
    if (kv) data[kv[1].trim()] = kv[2].trim();
  }
  return { data, rest: content.slice(m[0].length) };
}
function toTags(raw) {
  if (!raw) return [];
  if (Array.isArray(raw)) return raw.map(String);
  return String(raw).split(/[\s,，]+/).filter(Boolean);
}
var ArticlePreviewModal = class extends import_obsidian.Modal {
  constructor(app, html, onSave) {
    super(app);
    this.html = html;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("note-to-site-modal");
    contentEl.createEl("h3", { text: "\u7F51\u7AD9\u6587\u7AE0\u9884\u89C8\uFF08HTML \u6E90\u7801\uFF09" });
    const pre = contentEl.createEl("pre");
    pre.addClass("note-to-site-pre");
    pre.setText(this.html);
    const actions = contentEl.createDiv({ cls: "note-to-site-actions" });
    const copyBtn = actions.createEl("button", { text: "\u590D\u5236 HTML", cls: "mod-cta" });
    copyBtn.addEventListener("click", async () => {
      try {
        await navigator.clipboard.writeText(this.html);
        new import_obsidian.Notice("\u6587\u7AE0 HTML \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
      } catch (e) {
        new import_obsidian.Notice("\u590D\u5236\u5931\u8D25\uFF1A\u65E0\u6CD5\u8BBF\u95EE\u526A\u8D34\u677F");
      }
    });
    const saveBtn = actions.createEl("button", { text: "\u4FDD\u5B58\u5230\u7B14\u8BB0\u5E93" });
    saveBtn.addEventListener("click", async () => {
      try {
        await this.onSave();
        this.close();
      } catch (e) {
        new import_obsidian.Notice(`\u4FDD\u5B58\u5931\u8D25\uFF1A${e.message || "\u672A\u77E5\u9519\u8BEF"}`);
      }
    });
    const closeBtn = actions.createEl("button", { text: "\u5173\u95ED" });
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var NoteToSitePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("globe", "\u751F\u6210\u7F51\u7AD9\u6587\u7AE0\uFF08Note to Site\uFF09", () => {
      void this.generateArticle();
    });
    this.addCommand({
      id: "note-to-site-generate",
      name: "\u751F\u6210\u7F51\u7AD9\u6587\u7AE0\u9875\u9762",
      callback: () => {
        void this.generateArticle();
      }
    });
    this.addCommand({
      id: "note-to-site-copy-summary",
      name: "\u590D\u5236 Markdown \u6458\u8981",
      callback: () => {
        void this.copyMarkdownSummary();
      }
    });
    this.addSettingTab(new NoteToSiteSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getActiveNote() {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    return (_a = view == null ? void 0 : view.file) != null ? _a : null;
  }
  /** 汇总笔记元信息：frontmatter → 兜底解析 → 默认值 */
  getNoteMeta(note, content) {
    var _a, _b, _c, _d, _e;
    const cached = (_b = (_a = this.app.metadataCache.getFileCache(note)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
    const naive = (_d = (_c = parseFrontmatter(content)) == null ? void 0 : _c.data) != null ? _d : {};
    const pick = (key, fallback) => {
      var _a2, _b2;
      return (_b2 = (_a2 = cached[key]) != null ? _a2 : naive[key]) != null ? _b2 : fallback;
    };
    const title = String(pick("title", "")).trim() || note.basename;
    const category = String(pick("category", this.settings.defaultCategory)).trim();
    const dateRaw = String(pick("date", "")).trim();
    const date = dateRaw && (0, import_obsidian.moment)(dateRaw).isValid() ? (0, import_obsidian.moment)(dateRaw).format("YYYY-MM-DD") : (0, import_obsidian.moment)().format("YYYY-MM-DD");
    const tags = toTags((_e = cached.tags) != null ? _e : naive.tags);
    return { title, category, date, tags };
  }
  /** 生成导语：AI 优先，失败则回退本地提取 */
  async buildLead(body, title) {
    let lead = extractLead(body, this.settings.leadMaxChars);
    if (this.settings.aiEnabled) {
      const ai = await this.summarizeWithAI(body, title);
      if (ai) {
        lead = stripMarkdown(ai).replace(/\s+/g, " ").trim() || lead;
      }
    }
    return lead;
  }
  /** 调用 OpenAI 兼容接口生成导语 */
  async summarizeWithAI(content, title) {
    var _a, _b, _c, _d;
    const base = this.settings.aiBaseUrl.trim().replace(/\/+$/, "");
    const prompt = this.settings.aiPrompt.replace(/\{\{title\}\}/g, title).replace(/\{\{content\}\}/g, content.slice(0, 8e3));
    try {
      const res = await (0, import_obsidian.requestUrl)({
        url: `${base}/chat/completions`,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...this.settings.aiApiKey.trim() ? { Authorization: `Bearer ${this.settings.aiApiKey.trim()}` } : {}
        },
        body: JSON.stringify({
          model: this.settings.aiModel,
          messages: [
            {
              role: "system",
              content: "\u4F60\u662F\u4E00\u4F4D\u8BA4\u771F\u8D1F\u8D23\u7684\u4E2A\u4EBA\u7F51\u7AD9\u7F16\u8F91\uFF0C\u64C5\u957F\u4E3A\u6587\u7AE0\u64B0\u5199\u81EA\u7136\u3001\u51C6\u786E\u7684\u4E2D\u6587\u5BFC\u8BED\u3002"
            },
            { role: "user", content: prompt }
          ],
          temperature: 0.7
        })
      });
      const text = (_d = (_c = (_b = (_a = res.json) == null ? void 0 : _a.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content;
      if (typeof text === "string" && text.trim()) return text.trim();
      new import_obsidian.Notice("AI \u6458\u8981\u8FD4\u56DE\u4E3A\u7A7A\uFF0C\u5DF2\u4F7F\u7528\u672C\u5730\u63D0\u53D6");
      return null;
    } catch (e) {
      console.error("[Note to Site] AI \u6458\u8981\u5931\u8D25\uFF1A", e);
      new import_obsidian.Notice(`AI \u6458\u8981\u5931\u8D25\uFF08${e.message || "\u672A\u77E5\u9519\u8BEF"}\uFF09\uFF0C\u5DF2\u4F7F\u7528\u672C\u5730\u63D0\u53D6`);
      return null;
    }
  }
  /** 生成完整网站文章 HTML 页面 */
  buildArticleHtml(opts) {
    const s = this.settings;
    const homeHref = escapeHtml(s.homeHref || "../index.html");
    const cssPath = escapeHtml(s.cssPath || "../css/style.css");
    const siteName = escapeHtml(s.siteName || "ChengC");
    const title = escapeHtml(opts.title);
    const category = escapeHtml(opts.category);
    const lead = escapeHtml(opts.lead);
    const metaDescription = escapeHtml(opts.metaDescription);
    const titleTag = escapeHtml((opts.title + (s.titleSuffix || "")).trim());
    const dateDisplay = (0, import_obsidian.moment)(opts.date).format("YYYY \u5E74 M \u6708 D \u65E5");
    return `<!DOCTYPE html>
<html lang="zh-CN" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${titleTag}</title>
  <meta name="description" content="${metaDescription}">
  <meta name="theme-color" content="#090910">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Noto+Sans+SC:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="${cssPath}">
  <style>${MINDMAP_CSS}</style>
</head>
<body class="article-page">
  <header class="site-header">
    <nav class="nav-shell" aria-label="\u6587\u7AE0\u5BFC\u822A">
      <a class="brand" href="${homeHref}">${siteName}</a>
      <div class="article-nav"><a href="${homeHref}#blog">\u2190 \u8FD4\u56DE\u535A\u5BA2</a><button id="articleTheme" class="theme-btn" type="button" aria-label="\u5207\u6362\u4E3B\u9898"><svg class="sun-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-width="2" d="M12 3v2m0 14v2M3 12h2m14 0h2M6 6l1.5 1.5m9 9L18 18m0-12-1.5 1.5m-9 9L6 18M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0z"/></svg><svg class="moon-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-width="2" d="M20 15.5A9 9 0 0 1 8.5 4 9 9 0 1 0 20 15.5z"/></svg></button></div>
    </nav>
  </header>
  <main class="article-shell">
    <article>
      <header class="article-header">
        <a class="article-category" href="${homeHref}#blog">${category}</a>
        <h1>${title}</h1>
        <p class="article-lead">${lead}</p>
        <div class="article-meta"><time datetime="${opts.date}">${dateDisplay}</time><span>\u7EA6 ${opts.readingMinutes} \u5206\u949F\u9605\u8BFB</span></div>
      </header>
      <div class="article-body">
${opts.bodyHtml}
${opts.outlineHtml}
${opts.mindmapHtml}
      </div>
      <footer class="article-footer"><a class="button secondary" href="${homeHref}#blog">\u2190 \u8FD4\u56DE\u535A\u5BA2\u5217\u8868</a><a class="button primary" href="${homeHref}#journal">\u770B\u770B\u6700\u8FD1\u52A8\u6001</a></footer>
    </article>
  </main>
  <script>
    const saved=localStorage.getItem('theme');
    const apply=t=>{document.documentElement.classList.toggle('light',t==='light');document.documentElement.classList.toggle('dark',t!=='light')};
    apply(saved||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'));
    document.getElementById('articleTheme').addEventListener('click',()=>{const next=document.documentElement.classList.contains('dark')?'light':'dark';apply(next);localStorage.setItem('theme',next)});
  <\/script>
</body>
</html>`;
  }
  /** 主流程：读取笔记 → 总结 → 渲染正文 → 弹窗预览 */
  async generateArticle() {
    const note = this.getActiveNote();
    if (!note) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u7BC7 Markdown \u7B14\u8BB0");
      return;
    }
    const content = await this.app.vault.read(note);
    const fm = parseFrontmatter(content);
    const body = fm ? fm.rest : content;
    const meta = this.getNoteMeta(note, content);
    const lead = await this.buildLead(body, meta.title);
    const metaDescription = lead.length > 110 ? lead.slice(0, 107) + "\u2026" : lead;
    const container = document.createElement("div");
    container.addClass("markdown-rendered");
    await import_obsidian.MarkdownRenderer.render(this.app, body, container, note.path, this);
    const headingList = [];
    Array.from(container.querySelectorAll("h2, h3")).forEach((h) => {
      var _a, _b;
      const text = (_b = (_a = h.textContent) == null ? void 0 : _a.trim()) != null ? _b : "";
      if (text) headingList.push({ level: h.tagName === "H2" ? 2 : 3, text });
    });
    let outlineHtml = "";
    if (this.settings.includeOutline && headingList.length) {
      outlineHtml = `
        <h2>\u6587\u7AE0\u5927\u7EB2</h2>
        <ul>
` + headingList.map((h) => `          <li>${escapeHtml(h.text)}</li>`).join("\n") + `
        </ul>`;
    }
    let mindmapHtml = "";
    if (this.settings.includeMindMap && headingList.length) {
      const tree = buildMindTree(meta.title, headingList);
      mindmapHtml = `
        <h2>\u672C\u6587\u601D\u7EF4\u5BFC\u56FE</h2>
        <div class="mm-wrap">
          <div class="mm-tree">
            <ul>${renderMindTree(tree)}
            </ul>
          </div>
        </div>`;
    }
    const readingMinutes = estimateReadingTime(stripMarkdown(body));
    const html = this.buildArticleHtml({
      title: meta.title,
      category: meta.category,
      date: meta.date,
      lead,
      metaDescription,
      readingMinutes,
      bodyHtml: container.innerHTML,
      outlineHtml,
      mindmapHtml
    });
    new ArticlePreviewModal(this.app, html, async () => {
      await this.saveToVault(html, meta.title);
    }).open();
  }
  /** 复制 Markdown 摘要（frontmatter + 导语 + 大纲 + 统计） */
  async copyMarkdownSummary() {
    const note = this.getActiveNote();
    if (!note) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u7BC7 Markdown \u7B14\u8BB0");
      return;
    }
    const content = await this.app.vault.read(note);
    const fm = parseFrontmatter(content);
    const body = fm ? fm.rest : content;
    const meta = this.getNoteMeta(note, content);
    const lead = await this.buildLead(body, meta.title);
    const headingList = collectHeadingsWithLevel(body);
    const outline = headingList.map((h) => h.text);
    const readingMinutes = estimateReadingTime(stripMarkdown(body));
    const charCount = stripMarkdown(body).length;
    const parts = [
      "---",
      `title: ${meta.title}`,
      `date: ${meta.date}`,
      `category: ${meta.category}`
    ];
    if (meta.tags.length) parts.push(`tags: [${meta.tags.join(", ")}]`);
    parts.push(`summary: ${lead}`);
    parts.push("---", "");
    parts.push(`> **\u6458\u8981**\uFF1A${lead}`, "");
    if (outline.length) {
      parts.push("## \u5927\u7EB2", "");
      parts.push(outline.map((o) => `- ${o}`).join("\n"), "");
    }
    if (this.settings.includeMindMap && headingList.length) {
      const renderMd = (node, indent) => "  ".repeat(indent) + `- ${node.label}` + (node.children.length ? "\n" + node.children.map((c) => renderMd(c, indent + 1)).join("\n") : "");
      parts.push("## \u601D\u7EF4\u5BFC\u56FE", "");
      parts.push(renderMd(buildMindTree(meta.title, headingList), 0), "");
    }
    parts.push(
      `> \u5B57\u6570\uFF1A\u7EA6 ${charCount} \u5B57 \xB7 \u9884\u8BA1\u9605\u8BFB\uFF1A\u7EA6 ${readingMinutes} \u5206\u949F`
    );
    const md = parts.join("\n");
    try {
      await navigator.clipboard.writeText(md);
      new import_obsidian.Notice("Markdown \u6458\u8981\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    } catch (e) {
      new import_obsidian.Notice("\u590D\u5236\u5931\u8D25\uFF1A\u65E0\u6CD5\u8BBF\u95EE\u526A\u8D34\u677F");
    }
  }
  /** 保存生成的 HTML 到笔记库（自动处理重名与文件夹） */
  async saveToVault(html, title) {
    const folder = (0, import_obsidian.normalizePath)(this.settings.outputFolder.trim() || "\u7F51\u7AD9\u8F93\u51FA");
    await this.ensureFolder(folder);
    const base = slugify(title) || "untitled";
    let path = (0, import_obsidian.normalizePath)(`${folder}/${base}.html`);
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(path)) {
      path = (0, import_obsidian.normalizePath)(`${folder}/${base}-${i}.html`);
      i++;
    }
    await this.app.vault.create(path, html);
    new import_obsidian.Notice(`\u5DF2\u751F\u6210\uFF1A${path}`);
  }
  async ensureFolder(path) {
    const parts = path.split("/");
    let cur = "";
    for (const p of parts) {
      if (!p) continue;
      cur = cur ? `${cur}/${p}` : p;
      if (!this.app.vault.getAbstractFileByPath(cur)) {
        await this.app.vault.createFolder(cur);
      }
    }
  }
};
var NoteToSiteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u6587\u7AE0\u683C\u5F0F").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u5206\u7C7B").setDesc("\u751F\u6210\u6587\u7AE0\u9875\u9762\u7684\u5206\u7C7B\u6807\u7B7E\uFF0C\u53EF\u88AB\u7B14\u8BB0 frontmatter \u7684 category \u8986\u76D6").addText(
      (t) => t.setPlaceholder("\u5B66\u4E60").setValue(this.plugin.settings.defaultCategory).onChange(async (v) => {
        this.plugin.settings.defaultCategory = v.trim() || "\u5B66\u4E60";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5BFC\u8BED\u6700\u5927\u5B57\u6570").setDesc("\u672C\u5730\u63D0\u53D6\u5BFC\u8BED\u65F6\u7684\u622A\u65AD\u957F\u5EA6\uFF08\u5B57\u7B26\uFF09\uFF0CAI \u6458\u8981\u4E0D\u53D7\u6B64\u9650\u5236").addText(
      (t) => t.setPlaceholder("120").setValue(String(this.plugin.settings.leadMaxChars)).onChange(async (v) => {
        const n = parseInt(v, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.leadMaxChars = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B\u6587\u7AE0\u5927\u7EB2").setDesc("\u5728\u6B63\u6587\u672B\u5C3E\u8FFD\u52A0\u7531 H2/H3 \u6807\u9898\u7EC4\u6210\u7684\u5927\u7EB2").addToggle(
      (t) => t.setValue(this.plugin.settings.includeOutline).onChange(async (v) => {
        this.plugin.settings.includeOutline = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B\u5F69\u8272\u601D\u7EF4\u5BFC\u56FE").setDesc("\u5728\u6587\u7AE0\u672B\u5C3E\u8FFD\u52A0\u5F69\u8272\u601D\u7EF4\u5BFC\u56FE\uFF1A\u6807\u9898\u4E3A\u4E2D\u5FC3\uFF0CH2 \u4E3A\u4E00\u7EA7\u5206\u652F\uFF08\u6BCF\u652F\u4E00\u8272\uFF09\uFF0CH3 \u4E3A\u4E8C\u7EA7\u5206\u652F").addToggle(
      (t) => t.setValue(this.plugin.settings.includeMindMap).onChange(async (v) => {
        this.plugin.settings.includeMindMap = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7F51\u7AD9\u8DEF\u5F84").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u7AD9\u70B9\u540D").setDesc("\u9875\u9762\u9876\u680F\u4E0E\u5E95\u90E8\u663E\u793A\u7684\u540D\u79F0").addText(
      (t) => t.setPlaceholder("ChengC").setValue(this.plugin.settings.siteName).onChange(async (v) => {
        this.plugin.settings.siteName = v.trim() || "ChengC";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u9996\u9875\u94FE\u63A5").setDesc("\u8FD4\u56DE\u535A\u5BA2\u6309\u94AE\u6307\u5411\u7684\u5730\u5740\uFF0Cposts \u76EE\u5F55\u5185\u901A\u5E38\u662F ../index.html").addText(
      (t) => t.setPlaceholder("../index.html").setValue(this.plugin.settings.homeHref).onChange(async (v) => {
        this.plugin.settings.homeHref = v.trim() || "../index.html";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6837\u5F0F\u8868\u8DEF\u5F84").setDesc("\u6587\u7AE0\u9875\u9762\u5F15\u7528\u7684 CSS \u8DEF\u5F84").addText(
      (t) => t.setPlaceholder("../css/style.css").setValue(this.plugin.settings.cssPath).onChange(async (v) => {
        this.plugin.settings.cssPath = v.trim() || "../css/style.css";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6807\u9898\u540E\u7F00").setDesc("\u6D4F\u89C8\u5668\u6807\u7B7E\u9875 <title> \u7684\u540E\u7F00\uFF0C\u5982 \u201C \xB7 ChengC\u201D").addText(
      (t) => t.setPlaceholder(" \xB7 ChengC").setValue(this.plugin.settings.titleSuffix).onChange(async (v) => {
        this.plugin.settings.titleSuffix = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58\u6587\u4EF6\u5939").setDesc("\u70B9\u51FB\u201C\u4FDD\u5B58\u5230\u7B14\u8BB0\u5E93\u201D\u65F6\uFF0C\u751F\u6210\u7684 HTML \u5728\u7B14\u8BB0\u5E93\u4E2D\u7684\u5B58\u653E\u8DEF\u5F84").addText(
      (t) => t.setPlaceholder("\u7F51\u7AD9\u8F93\u51FA").setValue(this.plugin.settings.outputFolder).onChange(async (v) => {
        this.plugin.settings.outputFolder = v.trim() || "\u7F51\u7AD9\u8F93\u51FA";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("AI \u6458\u8981\uFF08\u53EF\u9009\uFF09").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528 AI \u6458\u8981").setDesc("\u5F00\u542F\u540E\u8C03\u7528\u5927\u6A21\u578B\u751F\u6210\u5BFC\u8BED\uFF1B\u5173\u95ED\u65F6\u4F7F\u7528\u672C\u5730\u63D0\u53D6\uFF08\u65E0\u9700\u8054\u7F51\uFF09").addToggle(
      (t) => t.setValue(this.plugin.settings.aiEnabled).onChange(async (v) => {
        this.plugin.settings.aiEnabled = v;
        this.display();
        await this.plugin.saveSettings();
      })
    );
    if (this.plugin.settings.aiEnabled) {
      new import_obsidian.Setting(containerEl).setName("\u63A5\u53E3\u5730\u5740").setDesc("OpenAI \u517C\u5BB9\u63A5\u53E3\uFF0C\u5982 https://api.openai.com/v1 \u6216 http://localhost:11434/v1\uFF08Ollama\uFF09").addText(
        (t) => t.setValue(this.plugin.settings.aiBaseUrl).onChange(async (v) => {
          this.plugin.settings.aiBaseUrl = v;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u672C\u5730 Ollama \u7B49\u65E0\u9700\u5BC6\u94A5\u7684\u63A5\u53E3\u53EF\u7559\u7A7A").addText(
        (t) => t.setValue(this.plugin.settings.aiApiKey).onChange(async (v) => {
          this.plugin.settings.aiApiKey = v;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u5982 gpt-4o-mini / deepseek-chat / qwen2.5").addText(
        (t) => t.setValue(this.plugin.settings.aiModel).onChange(async (v) => {
          this.plugin.settings.aiModel = v.trim() || "gpt-4o-mini";
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("\u63D0\u793A\u8BCD").setDesc("\u6A21\u677F\u4E2D\u7684 {{title}} \u4E0E {{content}} \u4F1A\u88AB\u81EA\u52A8\u66FF\u6362").addTextArea(
        (t) => t.setValue(this.plugin.settings.aiPrompt).onChange(async (v) => {
          this.plugin.settings.aiPrompt = v;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};
