const STORAGE_KEY='chengc_posts';const DEFAULT_POSTS=[{id:'multi-book-qa',title:'我把 6 本书的知识点，做成了一个离线问答台',category:'study',content:'一个多书语义问答：6 本书 326 条知识点，语义检索 + 引用溯源，语义引擎随站托管、打开即用，回答每句都能找到出处。',date:'2026/09/22',builtin:true,url:'posts/multi-book-qa.html'},{id:'linux-commands',title:'Linux 命令速查：增删查改，一篇讲清楚',category:'study',content:'整理 WSL / Linux 终端里最常用的文件操作命令，按查、增、改、删四类分类，每条都配了人话解释，附 nano 与 vi 编辑器用法。',date:'2026/09/18',builtin:true,url:'posts/linux-commands.html'},{id:'schedule-query',title:'我开源了一个「空课查询系统」',category:'study',content:'一个纯前端的空课查询网页，支持课节多选、全天交集与值班表，选择周数、星期、课节即可查看该时段有空的干事与干部名单，MIT 开源。',date:'2026/09/14',builtin:true,url:'posts/schedule-query.html'},{id:'hello-world',title:'Hello World',category:'life',content:'你好，世界！欢迎来到 ChengC 的网站。这是我的第一篇博客，也是这个数字空间正式启程的记录。',date:'2026/06/19',builtin:true,url:'posts/hello-world.html'},{id:'summer-support-teaching',title:'我的“三下乡”丨岁月留夏韵，支教启新程',category:'life',content:'七日乡村支教里，少儿编程启蒙、红色诗歌朗诵和文艺展演串起了一段双向成长的青春记忆。',date:'2026/08/13',builtin:true,url:'posts/summer-support-teaching.html'},{id:'painting-the-countryside',title:'我的“三下乡”丨以丹青妆乡野，以热爱润童心',category:'life',content:'从支教课堂到“和美石章”墙绘，再到雨中的文艺展演，一次乡村实践记录了陪伴、协作与成长。',date:'2026/07/24',builtin:true,url:'posts/painting-the-countryside.html'}];let currentFilter='all',searchQuery='',posts=[];
function loadPosts(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');const local=Array.isArray(p)?p.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.content==='string'&&typeof x.date==='string'&&['study','life'].includes(x.category)):[];posts=[...local,...DEFAULT_POSTS.filter(d=>!local.some(p=>p.id===d.id))]}catch(e){console.warn('记录数据无法读取。',e);posts=[...DEFAULT_POSTS]}}
function savePosts(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(posts));return true}catch(e){console.error('记录保存失败。',e);alert('保存失败：浏览器存储空间可能已满。');return false}}
function escapeHtml(text){const div=document.createElement('div');div.textContent=String(text);return div.innerHTML}
function visiblePosts(){return posts.filter(p=>(currentFilter==='all'||p.category===currentFilter)&&(!searchQuery||`${p.title} ${p.content}`.toLowerCase().includes(searchQuery))).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function renderPosts(){const box=document.getElementById('postsContainer'),shown=visiblePosts();document.getElementById('postCount').textContent=`共 ${shown.length} 条`;if(!shown.length){const title=searchQuery?'没有找到匹配记录':currentFilter==='all'?'还没有任何记录':'这个分类暂无记录';box.innerHTML=`<div class="empty-state"><strong>${title}</strong><p>${searchQuery?'换个关键词试试。':'暂时还没有记录。'}</p></div>`;return}box.innerHTML=shown.map(p=>`<article class="post-card" data-post-id="${escapeHtml(p.id)}" data-url="${escapeHtml(p.url||'')}" role="link" tabindex="0" aria-expanded="false" aria-label="打开文章《${escapeHtml(p.title)}》"><div class="post-tags"><span class="post-tag tag-${p.category}">${p.category==='study'?'学习':'生活'}</span></div><time class="post-date">${escapeHtml(p.date)}</time><h3 class="post-title">${escapeHtml(p.title)}</h3><p class="post-content">${escapeHtml(p.content)}</p><span class="read-more">${p.url?'阅读全文 →':'展开全文 ↓'}</span>${p.builtin?'':`<div class="post-actions"><button class="delete-btn" type="button" data-delete-id="${escapeHtml(p.id)}" aria-label="删除《${escapeHtml(p.title)}》">删除</button></div>`}</article>`).join('')}
function setFilter(filter){currentFilter=filter;document.querySelectorAll('.filter-btn').forEach(b=>{const active=b.dataset.filter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});renderPosts()}
function deletePost(id){if(!confirm('确定要删除这条记录吗？'))return;posts=posts.filter(p=>p.id!==id);if(savePosts())renderPosts()}
function applyTheme(theme){document.documentElement.classList.toggle('light',theme==='light');document.documentElement.classList.toggle('dark',theme!=='light');document.querySelector('meta[name="theme-color"]').content=theme==='light'?'#f7f5fb':'#090910'}
const savedTheme=localStorage.getItem('theme');applyTheme(savedTheme||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));document.getElementById('themeToggle').addEventListener('click',()=>{const next=document.documentElement.classList.contains('dark')?'light':'dark';applyTheme(next);localStorage.setItem('theme',next)});
const menuToggle=document.getElementById('menuToggle'),navLinks=document.getElementById('navLinks');menuToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'关闭导航菜单':'打开导航菜单')});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));document.getElementById('searchInput').addEventListener('input',e=>{searchQuery=e.target.value.trim().toLowerCase();renderPosts()});const postsContainer=document.getElementById('postsContainer');function openPost(card){if(card.dataset.url){location.href=card.dataset.url;return}const open=card.classList.toggle('expanded');card.setAttribute('aria-expanded',String(open));card.querySelector('.read-more').textContent=open?'收起文章 ↑':'展开全文 ↓'}postsContainer.addEventListener('click',e=>{const b=e.target.closest('[data-delete-id]');if(b){deletePost(b.dataset.deleteId);return}const card=e.target.closest('.post-card');if(card)openPost(card)});postsContainer.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('post-card')){e.preventDefault();openPost(e.target)}});loadPosts();renderPosts();
document.getElementById('backToTop').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
